import {Platform, StyleSheet} from 'react-native';
import {
  BLACK,
  GREY,
  GREY_LIGHT2,
  HEIGHT,
  MILK,
  SECONDARY_COLOR,
  SEMI_PRIMARY_COLOR,
  WHITE,
  WIDTH,
} from '../../../global/theme';
import {
  open_sans_bold,
  satoshi,
  satoshi_black,
  satoshi_bold,
  satoshi_medium,
} from '../../../constants/data/fonts';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    height: HEIGHT,
    backgroundColor: WHITE,
    width: WIDTH,
    alignSelf: 'center',
    alignItems: 'center',
  },
  viewContainer: {
    width: WIDTH * 0.95,
    alignSelf: 'center',
    height: HEIGHT,
    paddingHorizontal: 20,
  },
  view1: {
    width: '100%',
    alignSelf: 'center',
    alignItems: 'center',
    marginTop: 20,
    height: HEIGHT - 100,
    paddingBottom: 20,
  },
  header: {
    width: '100%',
    marginTop: 15,
  },
  btn: {
    padding: 10,
    backgroundColor: GREY_LIGHT2,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 50,
    width: 45,
    height: 45,
  },
  v1: {
    marginTop: 20,
    marginBottom: 7,
    width: '100%',
  },
  text1: {
    fontSize: 20,
    fontFamily: satoshi_bold,
    color: BLACK,
    marginBottom: 5,
  },
  text11: {
    fontSize: 12.5,
    fontFamily: satoshi_medium,
    color: '#A5A5A5',
    marginBottom: 5,
  },
  v2: {
    flexGrow: 1,
    marginVertical: 20,
    alignItems: 'center',
    width: '100%',
    gap: 8,
    // justifyContent: 'center',
  },
  // v21: {
  //     marginVertical: 10,
  // },
  rowView: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 7,
  },
  text13: {
    fontSize: 12,
    fontFamily: satoshi_medium,
    color: GREY,
    marginBottom: 5,
  },
  icon: {
    width: 40,
    height: 40,
    marginBottom: 20,
  },
  inputCont1: {
    width: '100%',
    borderRadius: 12,
    padding: 10,
    borderWidth: 0.7,
    borderColor: '#ececec',
    fontSize: 12,
    color: 'black',
    fontFamily: satoshi_medium,
    backgroundColor: '#F8F8FA',
  },
  text: {
    fontSize: 13,
    fontFamily: satoshi_bold,
    marginVertical: 5,
    color: BLACK,
  },
  input1: {},
  v3: {
    width: '100%',
    padding: 15,
    borderRadius: 15,
    backgroundColor: GREY_LIGHT2,
    marginVertical: 10,
  },
  btn1: {
    marginVertical: 20,
    width: '90%',
  },
  text12: {
    fontSize: 12,
    color: SEMI_PRIMARY_COLOR,
    fontFamily: satoshi_black,
  },
  image: {
    width: WIDTH * 0.65,
    height: WIDTH * 0.65,
  },
  v21: {
    width: '100%',
    marginVertical: 20,
  },
  text14: {
    fontSize: 13,
    fontFamily: satoshi_bold,
    color: BLACK,
    marginBottom: 5,
  },
  v22: {
    width: '100%',
    marginVertical: 20,
    borderColor: '#D0D5DD',
    borderWidth: 1,
    borderRadius: 10,
    backgroundColor: WHITE,
    padding: 20,
  },
  v4: {
    borderRadius: 8,
    backgroundColor: GREY_LIGHT2,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#D0D5DD',
    marginBottom: 20,
    padding: 15,
    width: '100%',
  },
  rowViewN: {
    alignItems: 'center',
    flexDirection: 'row',
    width: '80%',
  },
  text15: {
    fontSize: 15,
    fontFamily: satoshi_bold,
    color: BLACK,
    marginBottom: 3,
  },
  text16: {
    fontSize: 11.5,
    fontFamily: satoshi,
    color: '#A5A5A5',
    width: '70%',
  },
  text17: {
    fontSize: 11,
    textAlign: 'center',
    marginVertical: 15,
    alignSelf: 'center',
    color: '#667085',
    width: '60%',
    lineHeight: 18,
  },
  uploadCont: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: WHITE,
    padding: 20,
    marginTop: 8,
    borderRadius: 8,
  },
});
