import {Platform, StyleSheet} from 'react-native';
import {
  BLACK,
  GREY,
  GREY_LIGHT2,
  HEIGHT,
  SEMI_PRIMARY_COLOR,
  WHITE,
  WIDTH,
} from '../../../global/theme';
import {
  open_sans_bold,
  satoshi,
  satoshi_bold,
  satoshi_medium,
} from '../../../constants/data/fonts';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    height: HEIGHT,
    backgroundColor: WHITE,
    width: WIDTH,
    alignSelf: 'center',
    alignItems: 'center',
  },
  viewContainer: {
    width: WIDTH * 0.95,
    alignSelf: 'center',
    height: HEIGHT,
    paddingHorizontal: 20,
  },
  view1: {
    width: '100%',
    alignSelf: 'center',
    alignItems: 'center',
    marginTop: 20,
    height: HEIGHT - 100,
  },
  header: {
    width: '100%',
    marginTop: 15,
  },
  btn: {
    padding: 10,
    backgroundColor: GREY_LIGHT2,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 50,
    width: 45,
    height: 45,
  },
  v1: {
    marginTop: 20,
    marginBottom: 7,
    width: '100%',
  },
  text1: {
    fontSize: 18,
    fontFamily: satoshi_bold,
    color: BLACK,
    marginBottom: 5,
  },
  text11: {
    fontSize: 12.5,
    fontFamily: satoshi_medium,
    color: '#A5A5A5',
    marginBottom: 5,
  },
  v2: {
    flexGrow: 1,
    marginVertical: 20,
    alignItems: 'center',
    width: '100%',
    // justifyContent: 'center',
  },
  // v21: {
  //     marginVertical: 10,
  // },
  rowView: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 7,
  },
  text13: {
    fontSize: 12,
    fontFamily: satoshi_medium,
    color: GREY,
    marginBottom: 5,
  },
  icon: {
    width: 15,
    height: 15,
    marginRight: 10,
    marginTop: -5,
  },
  inputCont1: {},
  input1: {},
  v3: {
    width: '100%',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  btn1: {
    marginVertical: 20,
    width: '90%',
  },
  text12: {
    fontSize: 12,
    color: SEMI_PRIMARY_COLOR,
    fontFamily: satoshi_bold,
  },
  image: {
    width: WIDTH * 0.65,
    height: WIDTH * 0.65,
    // marginVertical: "10%"
  },
  v21: {
    width: '100%',
    marginVertical: 20,
  },
  text14: {
    fontSize: 13,
    fontFamily: satoshi_bold,
    color: BLACK,
    marginBottom: 5,
  },
  v22: {
    width: '100%',
    marginVertical: 20,
    borderColor: '#D0D5DD',
    borderWidth: 1,
    borderRadius: 10,
    backgroundColor: WHITE,
    padding: 20,
  },
  v4: {
    borderRadius: 8,
    backgroundColor: GREY_LIGHT2,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#D0D5DD',
    marginBottom: 20,
    padding: 15,
    width: '100%',
  },
  rowViewN: {
    alignItems: 'center',
    flexDirection: 'row',
    width: '80%',
  },
  text15: {
    fontSize: 15,
    fontFamily: satoshi_bold,
    color: BLACK,
    marginBottom: 3,
  },
  text16: {
    fontSize: 11.5,
    fontFamily: satoshi,
    color: '#A5A5A5',
    width: '70%',
  },
  text17: {
    fontSize: 11,
    textAlign: 'center',
    marginVertical: 15,
    alignSelf: 'center',
    color: '#667085',
    width: '60%',
    lineHeight: 18,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'flex-end',
    padding: 10,
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    width: '100%',
    height: '80%',
    backgroundColor: WHITE,
    borderRadius: 20,
    padding: 20,
  },
  searchInput: {
    height: 40,
    borderColor: '#D0D5DD',
    backgroundColor: '#F8F8FA',
    color: 'black',
    borderWidth: 1,
    borderRadius: 5,
    paddingHorizontal: 10,
    marginBottom: 10,
  },
  countryItem: {
    padding: 10,
  },
  countryText: {
    fontSize: 16,
    color: BLACK,
  },
  closeButton: {
    marginTop: 20,
    alignItems: 'center',
    paddingVertical: 10,
  },
  closeButtonText: {
    fontSize: 16,
    color: BLACK,
  },
});
